version: '3'
networks:
  home-inspector-network:
    driver: overlay

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.1
    networks:
      home-inspector-network:
        aliases:
          - home-inspector.elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.1.1
    networks:
      home-inspector-network:
        aliases:
          - home-inspector.kibana